dist: focal

git:
  depth: false

language: python
cache:
  - pip
  - dependencies

python:
  - "3.8"

install:
  - pip install -r docs/requirements.txt

script:
  - python -m pytest --black ./

notifications:
  email: false
